server:
  port: 8080
  servlet:
    context-path: /api
  undertow:
    url-charset: UTF-8

spring:
  application:
    name: demo
    admin:
      enabled: false

springdoc:
  api-docs:
    version: openapi_3_0
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    csrf:
      enabled: true
